id: I46540E8D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T11:07:55+00:00'
last_modified: '2022-06-08T11:27:10.480602+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30073
  title: ཀུན་དགའ་གྲོལ་མཆོག་གི་ཕྱི་ནང་གསང་གསུམ་གྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    29C3:
      image_group_id: I5793
      title: ''
      total_pages: 600
      order: 1
      base_file: 29C3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
