id: P009497
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 19:41:27.902174
source_metadata:
  id: bdr:W30073
  title: ཀུན་དགའ་གྲོལ་མཆོག་གི་ཕྱི་ནང་གསང་གསུམ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    231386f9fea94ec9b439581e8f0dabfd:
      image_group_id: I5793
      title: ''
      volume_number: 1
      total_pages: 600
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
