id: P009497
initial_creation_type: ocr
source_metadata:
  id: bdr:W30073
  title: ཀུན་དགའ་གྲོལ་མཆོག་གི་ཕྱི་ནང་གསང་གསུམ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    231386f9fea94ec9b439581e8f0dabfd:
      image_group_id: I5793
      title: ''
      volume_number: 1
      total_pages: 600
      base_file: v001.txt
